#Praktikum 1

In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2655529933008129
Epoch 1000, Loss: 0.25019573226036784
Epoch 2000, Loss: 0.2497054225357766
Epoch 3000, Loss: 0.24809564163930045
Epoch 4000, Loss: 0.23006160440788337
Epoch 5000, Loss: 0.11644535237074954
Epoch 6000, Loss: 0.02488539238070605
Epoch 7000, Loss: 0.010854365876961675
Epoch 8000, Loss: 0.006581928305737093
Epoch 9000, Loss: 0.004631553379062043
Prediksi:
[[0.06016104]
 [0.94526047]
 [0.93102247]
 [0.05278357]]


#Tugas

In [ ]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# --- PERUBAHAN DI SINI ---
input_size = 2
hidden_size = 3  # Mengubah jumlah neuron hidden layer menjadi 3
output_size = 1
lr = 0.1
# -------------------------

np.random.seed(42) # Agar perbandingan fair
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

print("--- Training dengan 3 Hidden Neurons ---")
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Error
    error = y - a2

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("Prediksi (3 Hidden Neurons):")
print(a2)

--- Training dengan 3 Hidden Neurons ---
Epoch 0, Loss: 0.31824520886068175
Epoch 1000, Loss: 0.20569699294249036
Epoch 2000, Loss: 0.1418539809567309
Epoch 3000, Loss: 0.058651326187686294
Epoch 4000, Loss: 0.020112046660991083
Epoch 5000, Loss: 0.009992200114726162
Epoch 6000, Loss: 0.006269504240552608
Epoch 7000, Loss: 0.004460666233485042
Epoch 8000, Loss: 0.003421033634262056
Epoch 9000, Loss: 0.0027556015957289
Prediksi (3 Hidden Neurons):
[[0.02515564]
 [0.95263635]
 [0.95122343]
 [0.0627247 ]]


In [ ]:
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

input_size = 2
hidden_size = 3 # Tetap menggunakan 3 neuron sesuai tugas sebelumnya
output_size = 1
lr = 0.1

np.random.seed(42)
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# --- DEFINISI FUNGSI BARU ---
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    # Turunan ReLU adalah 1 jika x > 0, dan 0 jika x <= 0
    return (x > 0).astype(float)
# -----------------------------

print("\n--- Training dengan ReLU (Hidden) & Sigmoid (Output) ---")
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)           # MENGGUNAKAN RELU DI HIDDEN LAYER

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)        # TETAP SIGMOID DI OUTPUT

    # Error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    # Backprop ke Hidden Layer (Gunakan turunan ReLU)
    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

print("Prediksi (ReLU):")
print(a2)


--- Training dengan ReLU (Hidden) & Sigmoid (Output) ---
Epoch 0, Loss: 0.3274780407035275
Epoch 1000, Loss: 0.012797082733424602
Epoch 2000, Loss: 0.003283471866346602
Epoch 3000, Loss: 0.001730956726043575
Epoch 4000, Loss: 0.001146816158135167
Epoch 5000, Loss: 0.0008463615651895275
Epoch 6000, Loss: 0.0006661559173500909
Epoch 7000, Loss: 0.0005467478016979456
Epoch 8000, Loss: 0.00046239544032793036
Epoch 9000, Loss: 0.0003996816119159116
Prediksi (ReLU):
[[0.02970009]
 [0.98605912]
 [0.98605934]
 [0.01163533]]
